[package]
name = "plain"
version = "0.2.3"
edition = "2018"
authors = ["jzr"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/randomites/plain"
homepage = "https://github.com/randomites/plain"
documentation = "https://docs.rs/plain"
description = "A small Rust library that allows users to reinterpret data of certain types safely."

categories = ["no-std", "data-structures", "parsing"]
keywords = ["plain", "pod", "ffi", "memory"]

